### ISSUE TITLE
Apple Music and Spotify support

### ISSUE THREAD

**Issue by GoldenChaos** [drensin/Remixatron#7]
Now that all my dreams have come true...

A not insignifcant part of my library is now hosted on Apple Music, and for others Spotify I’m sure. Both services provide direct song links and APIs to stream music - so it should now be possible to implement Apple Music in addition to Spotify.

Proposed syntax:

`python infinite_jukebox.py https://song.url`

**Comment by drensin** [comment]
Actually, this isn't possible/allowed. I need the complete audio buffer in order to do the analysis and it's _definitely_ against the terms of service for all streaming services to download and store the streaming audio.  Even if it weren't, the streaming urls send the playback bytes as needed so it would take the length of the song to retrieve it.

**Comment by GoldenChaos** [comment]
Ahhh, dang. It was worth a shot!
